services:
  - type: web
    name: saveinstayutubetgbot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        scope: run
